# 预编译模式：本地先执行 npm install && npm run build，Docker 直接打包 dist
FROM registry.cn-hangzhou.aliyuncs.com/library/nginx:alpine

COPY dist/ /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 7000
